---
services:
  db:
    image: rohitryali9/library:db
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
  auth_service:
    image: rohitryali9/library:auth
    ports:
      - "5001:5001"
    deploy:
      replicas: 3
    depends_on:
      - db
  book_service:
    image: rohitryali9/library:book
    ports:
      - "5002:5002"
    deploy:
      replicas: 3
    depends_on:
      - db
  borrow_service:
    image: rohitryali9/library:borrow
    ports:
      - "5003:5003"
    deploy:
      replicas: 3
    depends_on:
      - db
  app_service:
    image: rohitryali9/library:app
    ports:
      - "5000:5000"
    deploy:
      replicas: 3
    depends_on:
      - auth_service
      - book_service
      - borrow_service
